- hosts: localhost
  connection: local
 
  vars:
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - loadimpact/k6

    homebrew_cask_packages:
      - name: minikube
      - name: virtualbox
      - name: java8
      - name: java
      - name: docker
      - name: google-japanese-ime
      - name: google-cloud-sdk
      - name: alfred
      - name: appcleaner
      - name: atom
      - name: google-chrome
      - name: firefox
      - name: slack
      - name: coteditor
      - name: postman
      - name: iterm2
      - name: evernote
      - name: sourcetree
 
    homebrew_packages:
      - name: ansible
      - name: python
      - name: python3
      - name: kubectl
      - name: ripgrep
      - name: emacs
      - name: terraform
      - name: the_silver_searcher
      - name: tmux
      - name: zsh
      - name: ffmpeg
      - name: bazel
      - name: autoconf
      - name: go-delve/delve/delve
      - name: k6
      - name: libev
      - name: maven
      - name: node
      - name: peco
      - name: redis
      - name: protobuf
      - name: kubernetes-helm
      - name: go
      - name: trash
      - name: dep

    go_get:
      - name: kingpin
        url: gopkg.in/alecthomas/kingpin.v2
      - name: godef
        url: github.com/rogpeppe/godef
      - name: gocode
        url: github.com/nsf/gocode
      - name: golint
        url: github.com/golang/lint/golint
      - name: errcheck
        url: github.com/kisielk/errcheck
      - name: grpc
        url: google.golang.org/grpc
      - name: protoc-gen-go
        url: github.com/golang/protobuf/protoc-gen-go
      - name: zap
        url: go.uber.org/zap
      - name: testify
        url: github.com/stretchr/testify
      - name: flymake
        url: github.com/dougm/goflymake
      - name: gomock
        url: github.com/golang/mock/gomock
      - name: mockgen
        url: github.com/golang/mock/mockgen

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes
 
    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'
 
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
 
    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: golang packages install
      shell: "go get -u {{ item.url }}"
      with_items: "{{ go_get }}"
      changed_when: false
